version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - PYTHONPATH=/backend
      - FLASK_ENV=development
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules