name: "URL shortener CI"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
        
            - name: Build backend
              run: |
                cd backend
                docker build -t test-repo:backend .

            - name: Build frontend
              run: |
                cd frontend
                docker build -t test-repo:frontend .
            
            # Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Push both images to same repository with different tags
            - name: Push images
              run: |
                docker tag test-repo:backend ${{ secrets.DOCKERHUB_USERNAME }}/test-repo:backend
                docker tag test-repo:frontend ${{ secrets.DOCKERHUB_USERNAME }}/test-repo:frontend
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-repo:backend
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-repo:frontend