name: "URL shortener CI"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses : actions/checkout@v2
        
            - name: Build backend
              run : |
                cd backend
                docker build -t urlshortener-backend .

            - name: Build frontend
              run : |
                cd frontend
                docker build -t urlshortener-frontend .

            # Add after your build steps
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push images
              run: |
                docker tag urlshortener-backend ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-backend:latest
                docker tag urlshortener-frontend ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-frontend:latest
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-backend:latest
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/urlshortener-frontend:latest